### ISSUE TITLE
Bundler 1.14.x cannot install hash_kit 0.4.8

### ISSUE THREAD

**Issue by cpetschnig** [vaughanbrittonsage/hash_kit#5]
With a new version of bundler, the newest version of hash_kit cannot be installed.

According to https://github.com/rubygems/rubygems.org/issues/1551 and https://github.com/bundler/bundler/issues/5332, the solution is to release a new version of the gem.

```
Bundler cannot continue installing hash_kit (0.4.8).
The checksum for the downloaded `hash_kit-0.4.8.gem` does not match the checksum
given by the server. This means the contents of the downloaded gem is different
from what was uploaded to the server, and could be a potential security issue.

To resolve this issue:
1. delete the downloaded gem located at:
`/usr/lib/ruby/gems/2.3.0/gems/hash_kit-0.4.8/hash_kit-0.4.8.gem`
2. run `bundle install`

If you wish to continue installing the downloaded gem, and are certain it does
not pose a security issue despite the mismatching checksum, do the following:
1. run `bundle config disable.checksum_validation true` to turn off checksum
verification
2. run `bundle install`

(More info: The expected SHA256 checksum was
"f7ae2829a96761a0569eac8f20066038c6ace083b797465d19e2a6f03aa3af94", but the
checksum for the downloaded gem was
"e4c66f4c62f66946de11fbbd9839b8cce78f89661977ae03b551e446dc729c8e".)
```
(from https://app.codeship.com/projects/184238/builds/ea93e8cf-bc4a-4440-81cc-3a846a0b3423, if you have access)

**Comment by chrisbarber86** [comment]
@cpetschnig I believe this repo is hooked up to automatically deploy a new version to rubygems when a tag is created, so feel free to cut `v0.4.9` from master to force it to redeploy a new version.

cc @vaughanbrittonsage

**Comment by vaughanbrittonsage** [comment]
I'll cut a new version of the gem `v0.4.9` this repo is hooked up to deploy new tags to ruby gems via Travis. So anyone with push permissions can release versions of this gem.

**Comment by cpetschnig** [comment]
This fixed it, thanks!
